// src/components/Footer.jsx
import React from 'react';

export default function Footer(props) {
    return (
        <footer className="hero hero-sm bg-secondary">
            <div className="hero-body">
                <p className="text-center">
                    Copyright &copy; 2020 Aidan T. Manning under the <a href="https://github.com/periodicaidan/portfolio/blob/React/LICENSE">MIT License</a>.
                    <br/>
                    This website and its <a href="https://github.com/periodicaidan/portfolio/tree/React">source code</a> are free to use.
                </p>
            </div>
        </footer>
    )
}

// src/components/Footer.svelte
<footer class="hero hero-sm bg-secondary">
  <div class="hero-body">
    <p class="text-center">
      Copyright &copy; 2020 Aidan T. Manning under the <a href="https://github.com/periodicaidan/portfolio/blob/Svelte/LICENSE">MIT License</a>. 
      <br>
      This website and its <a href="https://github.com/periodicaidan/portfolio/tree/Svelte">source code</a> are free to use.
    </p>
  </div>
</footer>
