// src/components/Hero/index.jsx
import React from 'react';
import './Hero.css';

export default function Hero(_props) {
    return (
        <div id="banner" className="hero hero-lg bg-primary">
            <div className="hero-body">
                <h1 className="text-center">Aidan T. Manning</h1>
                <p className="text-center text-large" style={{ textShadow: '0 0 0.3em black' }}>
                    Software engineer with a chemistry background. <br />
                    Analytical-minded, solution-oriented, evidence-driven. <br />
                    Proficient in front- and back-end web technologies. <br />
                    Enthusastic about Rust and low-level/systems programming. <br />
                    Almost a decade of technical writing experience. <br />
                    Life is an optimization problem.
                </p>
            </div>
        </div>
    );
}

// src/components/Hero.svelte
<div id="banner" class="hero hero-lg bg-primary">
  <div class="hero-body">
    <h1 class="text-center">Aidan T. Manning</h1>
    <p class="text-center text-lightly">
      Software engineer with background in chemistry. <br>
      Analytically-minded, solution-oriented, evidence-driven. <br>
      Proficient in front- and back-end web technologies. <br>
      Enthusiastic about Rust and low-level/systems programming. <br>
      Almost a decade of technical writing experience. <br>
      Life is an optimization problem.
    </p>
  </div>
</div>

<style>
  #banner {
    background: linear-gradient(rgba(22, 17, 44, 0.2), rgba(22, 17, 44, 0.6)), url('../assets/images/vaporwaveshit.jpg') no-repeat fixed center top !important;
    background-size: cover !important;
  }

  #banner .hero-body {
    text-shadow: 0 0 0 1em brown;
  }
</style>
