// src/components/Navbar.svelte
<script lang="ts">
  import SocialMediaItem from './SocialMenuItem.svelte';
  import socialMediaData from '../data/socials';
import SocialMenuItem from './SocialMenuItem.svelte';
</script>

<header class="navbar">
  <!-- Left Section -->
  <section class="navbar-section">
    <a href="/" class="btn btn-link">guest@github.io</a>
  </section>

  <!-- Middle/Brand/Logo thing -->
  <section class="navbar-center">
    <!-- TODO: Come up with a logo to include in the middle section -->
    <b class="text-bold">pa</b>
  </section>

  <!-- Right Section -->
  <section class="navbar-section">
    <a href="assets/ATManningResume.pdf" target="_blank" rel="noopener noreferrer" class="btn btn-link">resume</a>
    <div class="popover popover-bottom">
      <a href="#" class="btn btn-link">socials</a>
      <div class="popover-container">
        <ul class="menu">
          {#each socialMediaData as social}
            <SocialMenuItem {...social} />
          {/each}
        </ul>
      </div>
    </div>
  </section>
</header>

<style>
  header.navbar {
    width: 80% !important;
    margin: auto !important;
  }
</style>

// src/components/NavBar.jsx
import React from 'react';
import socialMediaData from '../data/socials.json';

export default function NavBar(_props) {
    return (
        <header className="navbar" style={{ width: '80%', margin: 'auto' }}>
            {/* Left section */}
            <section className="navbar-section">
                <a href="/" className="btn btn-link">guest@github.io</a>
            </section>

            {/* Middle/Brand/Logo thing */}
            <section className="navbar-center">
                {/* TODO: Come up with a logo and include it in the middle section */}
                <b className="text-bold">pa</b>
            </section>

            {/* Right section */}
            <section className="navbar-section">
                <a href="assets/ATManningResume.pdf" target="_blank" rel="noreferrer" className="btn btn-link">resume</a>
                <div className="popover popover-bottom">
                    <a href="#" className="btn btn-link">socials</a>
                    <div className="popover-container">
                        <ul className="menu">
                            {socialMediaData.map(social => <SocialMenuItem {...social} />)}
                        </ul>
                    </div>
                </div>
            </section>
        </header>
    );
}

function SocialMenuItem({ name, url, icon }) {
    return (
        <li className="menu-item">
            <a 
                href={url} 
                className="btn btn-link tooltip"
                target="_blank"
                rel="noreferrer"
                data-tooltip={name}
            >
                <i className={icon}></i>
            </a>
        </li>
    );
}
