// src/components/ProjectCard.jsx
import React from 'react';

export default function ProjectCard(props) {
    const { title, lang, description } = props;
    const { githubHosted, name } = props;
    const owner = props.owner ?? 'periodicaidan';

    const { repo, demo } = githubHosted 
        ? { 
            repo: `https://github.com/${owner}/${name}`, 
            demo: `https://${owner}.github.io/${name}` 
        }
        : props;
    
    return (
        <div className="column col-6 col-md-12 my-2">
            <div className="card">
                <div className="card-header">
                    <h4 className="card-title">{title}</h4>
                    <span className="card-subtitle text-gray text-uppercase">{lang}</span>
                </div>
                <div className="divider" />
                <div className="card-body">
                    {description}
                </div>
                <div className="card-footer">
                    <a href={demo} target="_blank" class="btn btn-success" disabled={demo == null}>Demo</a>
                    <a href={repo} target="_blank" class="btn btn-secondart">Repo</a>
                </div>
            </div>
        </div>
    );
}

// src/components/ProjectCard.svelte
<script lang="ts">
  export let title: string;
  export let lang: string;
  export let description: string;
  export let githubHosted: boolean;
  export let name: string;
  export let owner = 'periodicaidan';
  export let repo = githubHosted && `https://github.com/${owner}/${name}`;
  export let demo = githubHosted && `https://${owner}.github.io/${name}`;
</script>

<div class="column col-6 col-md-12 my-2">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">{title}</h4>
      <span class="card-subtitle text-gray text-uppercase">{lang}</span>
    </div>
    <div class="divider" />
    <div class="card-body">
      {description}
    </div>
    <div class="card-footer">
      <a href={demo} target="_blank" rel="noopener noreferrer" class="btn btn-success" disabled={!demo}>Demo</a>
      <a href={repo} target="_blank" rel="noopener noreferrer" class="btn btn-secondary">Repo</a>
    </div>
  </div>
</div>
